### ISSUE TITLE
Strapi / Organization dividers

### ISSUE THREAD

**Issue by joonasnuutinen** [yaguzmang/ghg-emission-calculation-tool#71]
Add organization divider collection type that lets the user to add an arbitrary number of dividers (name) to an organization. Then add a repeating component to organization unit that lets the user to define divider–value pairs for an organization unit.

For example:

Dividers:
- Personnel
- Floor area (m2)
- Revenue (M€)

Organization unit 1:
- Personnel: 100
- Floor area: 1000
- Revenue: 10

Organization unit 2:
- Personnel: 50
- Floor area: 600
- Revenue: 4

## Tasks

- [x] Edit schemas
- [ ] Edit an existing organization's dividers
- [ ] Create an organization unit with divider values
- [ ] Edit an existing organization unit with divider values
