### ISSUE TITLE
Strapi / Accuracy

### ISSUE THREAD

**Issue by joonasnuutinen** [yaguzmang/ghg-emission-calculation-tool#76]
## Description

Calculate the accuracy by scope.

![Image](https://user-images.githubusercontent.com/18427577/250043375-40e16cc7-18af-4c7c-8af7-9aacaabcfe3f.png)

Include it in the GET /reporting-periods/:id/emissions response. To achieve this, separate the current main `data` array into a property called `organizationUnits` and add a new property called `totalEmissions` with the following structure:

```json
{
  "data": {
    "totalEmissions": {
      "scope1": {
        "emissions": 123,
        "accuracy": 0.7
      },
      "scope2": {
        "emissions": 123,
        "accuracy": 0.7
      },
      "scope3": {
        "emissions": 123,
        "accuracy": 0.7
      },
      "biogenic": {
        "emissions": 123,
        "accuracy": 0.7
      }
    },
    "organizationUnits": [
      {
        "id": 1,
        "name": "Tallinn campus",
        "createdAt": "2023-04-14T04:27:52.180Z",
        "updatedAt": "2023-06-16T19:46:12.998Z",
        "emissions": {
          "scope1": [
            {
              "id": 1,
              "title": "Energy",
              "primaryScope": 1,
              "color": "#81D1DF",
              "emissions": 0.084
            }
          ],
          "scope2": [],
          "scope3": [],
          "biogenic": [
            {
              "id": 1,
              "title": "Energy",
              "primaryScope": 1,
              "color": "#81D1DF",
              "emissions": 133.29999999999998
            }
          ]
        }
      },
      {
        "id": 2,
        "name": "Tartu campus",
        "createdAt": "2023-04-14T04:28:06.848Z",
        "updatedAt": "2023-06-16T19:47:01.351Z",
        "emissions": {
          "scope1": [
            {
              "id": 1,
              "title": "Energy",
              "primaryScope": 1,
              "color": "#81D1DF",
              "emissions": 0.168
            }
          ],
          "scope2": [],
          "scope3": [
            {
              "id": 1,
              "title": "Energy",
              "primaryScope": 1,
              "color": "#81D1DF",
              "emissions": 200
            }
          ],
          "biogenic": [
            {
              "id": 1,
              "title": "Energy",
              "primaryScope": 1,
              "color": "#81D1DF",
              "emissions": 266.59999999999997
            }
          ]
        }
      },
      {
        "id": 4,
        "name": "Test campus 1",
        "createdAt": "2023-05-03T09:38:55.988Z",
        "updatedAt": "2023-06-21T08:45:17.833Z",
        "emissions": {
          "scope1": [
            {
              "id": 1,
              "title": "Energy",
              "primaryScope": 1,
              "color": "#81D1DF",
              "emissions": 0.023999999999999997
            }
          ],
          "scope2": [],
          "scope3": [
            {
              "id": 1,
              "title": "Energy",
              "primaryScope": 1,
              "color": "#81D1DF",
              "emissions": 0.026
            }
          ],
          "biogenic": [
            {
              "id": 1,
              "title": "Energy",
              "primaryScope": 1,
              "color": "#81D1DF",
              "emissions": 0.022000000000000002
            }
          ]
        }
      }
    ]
  }
}

```

The accuracy is calculated as a weighted average of the tiers, weighted by emissions. Thus, the accuracy will be a number between 0...3.

## Tasks

- [x] Move the emissions array to an `organizationUnits` property
- [x] Calculate the accuracy by scope
- [x] Enable Tier 0
- [x] Add new translations from #73
